[package]
name = "countdown"
version = "0.1.0"
edition = "2024"

[dependencies]
microbit-v2 = "0.16.0"
cortex-m = "0.7.9"
cortex-m-rt = "0.7.6"
panic-halt = "1.0.0"
rand = { version = "0.10.2", default-features = false }
# rtt-target = { version = "0.6.1" }
# panic-rtt-target = { version = "0.2.0" }

[dev-dependencies]
rtt-target = { version = "0.6.2" }
panic-rtt-target = { version = "0.2.0" }
